### ISSUE TITLE
创建索引过程中闪退

### ISSUE THREAD

**Issue by iptop** [neal1991/everywhere#3]
电脑内存8g空闲内存4g左右创建索引的过程中程序闪退了，是因为的我电脑上的文件太多了？

**Comment by neal1991** [comment]
应该是这样的问题，很有可能是OutOfMemory，我最近也一直被这个问题困扰，可以尝试通过`config.yaml`中的`excludePathList`里面配置减少扫描的路径，后续想办法能不能优化。

**Comment by neal1991** [comment]
@iptop 用了一个很简单的思路解决这个问题，可能有效，可以尝试尝试最新版本。
